version: "3.1"
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: auditoria
            MYSQL_PASSWORD: prii123
            MYSQL_ROOT_PASSWORD: prii123 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 9000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: prii123
            MYSQL_ROOT_PASSWORD: prii123
volumes:
    persistent: